### ISSUE TITLE
bootstrap-editable-inline is out of date

### ISSUE THREAD

**Issue by ekolvets** [klenis/bootstrap-x-editable-rails#1]
The version of boostrap-editable-inline is version 1.3.0 .  I don't believe its necessary to have a separate version since you can specify the mode using:

$.fn.editable.defaults.mode = 'inline';

In which case, the file vendor / assets / javascripts / bootstrap-editable-inline.js could be removed and the mention of it in the docs.

**Comment by klenis** [comment]
Nice! I totally missed that :)
