### ISSUE TITLE
Documentation on how to use this gem

### ISSUE THREAD

**Issue by ydemissie** [klenis/bootstrap-x-editable-rails#5]
Hi, is there documentation somewhere that shows how to use this gem? I'm using Rails 4 and I have installed the gem but I have no idea where to go from there. Thanks!

**Comment by klenis** [comment]
This gem only helps you with adding X-editable to the asset pipeline. This includes handling image assets used in the X-editable project. The documentation for this gem is located in the README file. After completing the steps in the documentation you have to turn to the original X-editable project for details on how to activate the X-editable plugin. It's actually really straightforward once you start using it.

**Comment by ydemissie** [comment]
Ok, thanks for getting back to me!

**Comment by ydemissie** [comment]
Hi Klenis,

Sorry to bother you again. I looked at the x-editable documentation and did a quick test by adding the following code straight into my view. The field appears on the page in the same format I see on the x-editable page but nothing happens when I click on it. With your gem having placed x-editable in the rails asset pipeline, I thought that’s all I needed to do. What I am missing here? Sorry to bug you on this. If only I could get it going rails then I can do the rest using the x-editable documentation.

<div class="form-group">
    <label class="col-sm-4">Service Charges</label>
    <div class="col-sm-6 hoverEdit">
        <a class="editableAccount" id="serviceTax"></a>
    </div>
</div>

<script>
$('.editableAccount').editable({
    type : 'number',
    step: 'any',
    title : 'Enter New Value',
    success : function(response, newValue) {
        updateAccount(this.id, newValue);
    }
});</script>

Thanks,

Yared

**Comment by ydemissie** [comment]
Adding these lines to my test view got x-editable working. I thought part of your gem’s job was to have these available as part of the pipeline. I’m trying to wrap my head around what rails needs and what your gem makes available in the asset pipeline. Is there even a need to install bootstrap and bootstrap-x-editable in rails? It’s too bad I have to put the lines below in every page I want to use x-editable when I have the gem installed…

```
<!-- Bootstrap - JAVASCRIPT - -->

<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<!-- bootstrap-editable js -->

<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
```

Thanks!

**Comment by klenis** [comment]
Hi,

There are many ways to include Bootstrap in your Rails project and for maximum flexibility I chose not to make that decision for the users of this gem. My personal recommendation is to use [bootstrap-sass](https://github.com/twbs/bootstrap-sass).

I don't know your reasons for including external scripts in your view. The recomended way is to include it in the `app/assets/javascripts/application.js`and `app/assets/stylesheets/application.css` as documented in the README of this gem. If you really need to do it in the views then the following is the correct way to do it.

CSS:

```
<%= stylesheet_link_tag "bootstrap3-editable/bootstrap-editable" %>
```

Javascript

```
<%= javascript_include_tag "bootstrap3-editable/bootstrap-editable" %>
```

Hope this helps you :)

**Comment by ydemissie** [comment]
That's what I was saying; following your readme did not work. The only way I had it working was by adding to the view. I have since removed it from my views into a helper file and it works. I'm not happy because your gem would be a more elegant solution but unfortunately your gem didn't work for me. I thought with your gem all I needed to do was to add my javascript code into my .js and .coffee files but it didn't work. But when I add the external scripts my javascript code works.

That's why I think adding a simple rails implementation example in your readme would really help figure out whether it's a user error or a gem issue. Just my opinion though...

Thanks for following up!

Cheers!

**Comment by klenis** [comment]
That is strange. I am using this gem myself in multiple projects (Rails 3 and Rails 4) and the only thing except the X-editable specific stuff is to include the files as written in the documentation. I will look into creating a sample Rails project to help people get started.

**Comment by ydemissie** [comment]
Yeah, it sounds like it's really not being included in the asset pipeline. I'm running rails 4.0.3. I'll try it in 4.0.4. Cheers!

**Comment by klenis** [comment]
OK, this was a quick one. This is my usual approach to trigger jQuery plugins in Rails by using data-attributes.

https://github.com/klenis/bootstrap-x-editable-rails-demo

Give it a go and if it is useful then let's add it to the the documentation.

**Comment by ydemissie** [comment]
Thanks for putting this together so quickly! I looked through your files and I didn’t see anything much different than my setup… interesting. I’ll clone it when I get home, try it out and let you know how it goes.

Cheers!

**Comment by ydemissie** [comment]
I cloned your demo and tested it and it worked. I created a test controller in my app and used your javascript and update action and it worked as well. Now I’ll just need to work backwards and see why my implementation doesn’t work. I think your demo would be immensely useful for your users so I would add it to the documentation if I were you.

I’ll break my app now by removing the external assets and make it work with your gem as it is the cleaner way to do it. Thanks so much, Klenis! You’re awesome!

**Comment by klenis** [comment]
I'm glad I could help :)

Thanks for testing the example project. I've added a link in the documentation.

**Comment by ydemissie** [comment]
Awesome, thanks! FYI, I got it working in my app as well so I'm happy. The only issue I need to sort out now is why when I first go to a page that has editable fileds, those fileds are not editable until I refresh the page.

Great gem, thanks!!

**Comment by GuanglinDu** [comment]
Dear klenis, the editing is enabled only once. After returning from other links, the pages have to be reloaded to enable the editing. This is annoying. Please help.
