### ISSUE TITLE
couldn't find file 'bootstrap3-editable/bootstrap-editable'

### ISSUE THREAD

**Issue by huhuanming** [klenis/bootstrap-x-editable-rails#6]
I don't  know how to solve this issuse.
Installed it by gem.
In my Gemfile,like this, gem 'bootstrap-x-editable-rails', '~> 1.5.1.1'.
but  it said "couldn't find file 'bootstrap3-editable/bootstrap-editable' "

**Comment by klenis** [comment]
Have a look and try the example project

https://github.com/klenis/bootstrap-x-editable-rails-demo

**Comment by ydemissie** [comment]
Make sure the gem has installed properly by doing:
gem list bootstrap-x-editable-rails

In your Gemfile you should have the following plus whatever else you need in your app:
gem 'bootstrap-sass'
gem 'bootstrap-x-editable-rails'

In your app/assets/javascripts/application.js file you should have the following plus whatever else you need in your app:

//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require bootstrap3-editable/bootstrap-editable
//= require_tree .

Your app/assets/stylesheets/application.css should have the following plus whatever else you need for your app:
 *= require_self
 *= require bootstrap
 *= require bootstrap3-editable/bootstrap-editable
 *= require_tree .
 */

Have you actually cloned the example project klenis provided above and played with it? If that example works in your environment then you should be able to make it work in your app. Once you've cloned it you can use the files in it to build your own app.
