### ISSUE TITLE
Having to refresh to enable editing again

### ISSUE THREAD

**Issue by GuanglinDu** [klenis/bootstrap-x-editable-rails#8]
In-place editing is enabled only once when opening the page at the first time. After leaving the page and going back again following other links, the page has to be refreshed to enable the editing.

**Comment by klenis** [comment]
Sounds like you're using Turbolinks or some other functionality that prevents full page reloads when clicking on links. If that's the case you need to retrigger the plugin. For Turbolinks you can use the `ajax:success` event.

**Comment by GuanglinDu** [comment]
Thanks. That's the very reason why the page has to be refreshed to enable editing again. I've disabled turbolinks in my app following this https://howilearnedrails.wordpress.com/2014/08/17/how-to-remove-turbolinks-from-rails-4/: (1) remove the turbolinks line in app/assets/javascripts/application.js, and (2) set javascript "data-turbolinks-track" => false in  app/views/layouts/application.html.erb. After this, in-place editing is always available.
